// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          pgtype.UUID
	User        pgtype.UUID
	Title       string
	Description pgtype.Text
	CompletedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	// prioridade da tarefa, quanto menor o valor mais prioridade terá, 1 é a prioridade mais alta.
	Priority pgtype.Int4
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Avatar    pgtype.Text
	Username  string
	Password  string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
