#####
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "deni42@email.com",
  "username": "denis",
  "password": "123456",
  "bio": "denis bio"
}
#####
#####
POST http://localhost:8080/api/users
Content-Type: application/json

{
"email": "denis2@email.com",
  "username": "denis2",
  "password": "123456",
  "bio": "denis bio2"
}
#####
#####

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "denis@email.com",
  "password": "123456"
}
#####
#####
GET http://localhost:8080/api/private/users
Accept: application/json
Authorization: Bearer {{keyJwt}}

#####
#####
GET http://localhost:8080/api/private/users
Accept: application/json
Authorization: Bearer {{keyJwt}}

#####
